name: meetings-ai
root: ~/Work/tweak-things/meetings-ai/

startup_window: main

windows:
  - shell:
  - claude:
      - alias run="tmux rename-window -t\${TMUX_PANE} 'claude'; clear; claude --dangerously-skip-permissions; tmux rename-window -t\${TMUX_PANE} '🔴 claude'"
      - run
  - transcript:
      - alias run="tmux rename-window -t\${TMUX_PANE} 'transcript'; clear; uv run main.py; tmux rename-window -t\${TMUX_PANE} '🔴 transcript'"
      - run
